version: "3.8"

services:

  postgres:
    container_name: USERS_DB_DEV
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: USERS_DB
    volumes:
      - SPRING_API_DB:/var/lib/postgresql/data
      - ./docker/postgres/shared/:/shared/
    restart: unless-stopped

  pgadmin:
    container_name: SPRING_API_PGADMIN
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: superadmin@springapi.org
      PGADMIN_DEFAULT_PASSWORD: superpassword
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/conf/server.json
    volumes:
      - ./docker/pgadmin/:/pgadmin4/conf/
    restart: unless-stopped

volumes:
  SPRING_API_DB:
