version: "3.7"

services:
  postgres:
    container_name: product-api-postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: PRODUCTS_DB
    volumes:
      - PRODUCT_API_POSTGRES_VOLUME:/var/lib/postgresql/data
      - ./docker/postgres/shared/:/shared/
    restart: unless-stopped
    networks:
      - interapi
      - apidb

  springbootapp:
    build: .
    container_name: product-api-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PRODUCTS_DB
      SPRING_DATASOURCE_USERNAME: super_admin
      SPRING_DATASOURCE_PASSWORD: super_password
    ports:
      - 8082:8080
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - apidb
      - interdb

  pgadmin:
    container_name: product-api-pgadmin
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: superadmin@productsapi.org
      PGADMIN_DEFAULT_PASSWORD: superpassword
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/conf/server.json
    volumes:
      - ./docker/pgadmin/:/pgadmin4/conf/
    restart: unless-stopped

volumes:
  PRODUCT_API_POSTGRES_VOLUME:

networks:
  interapi:
    name: productapi_interapi
    driver: bridge
  apidb:
    name: productapi_apidb
    driver: bridge
  default:
    name: productapi_default
    driver: bridge
  interdb:
    name: productapi_interdb
    driver: bridge
