version: "3.8"

services:

  postgres-users:
    container_name: USER_API_POSTGRES
    image: postgres:latest
    hostname: postgres
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: super_password
      POSTGRES_DB: USERS_DB
    volumes:
      - SPRING_API_USER_DB_VOLUME:/var/lib/postgresql/data
      - ./docker/postgres/shared/:/shared/
    restart: unless-stopped
    networks:
      - apidb

  springboot-user:
    build: .
    container_name: USER_API_SPRING
#    image: user-api:0.1
    ports:
      - 8093:8093
    depends_on:
      - postgres-users
    links:
      - postgres-users
    networks:
      - apidb

  pgadmin-users:
    container_name: USER_API_PGADMIN
    image: dpage/pgadmin4
    ports:
      - "4444:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: superadmin@springapi.org
      PGADMIN_DEFAULT_PASSWORD: superpassword
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/conf/server-prod.json
    volumes:
      - ./docker/pgadmin/:/pgadmin4/conf/
    restart: unless-stopped
    networks:
      - apidb

volumes:
  SPRING_API_USER_DB_VOLUME:

networks:
  apidb:
    name: network_db
    driver: bridge